export enum EnvVarKeys {
  TELEGRAM_BOT_TOKEN = 'TELEGRAM_BOT_TOKEN',
  MONGO_DB_URI = 'MONGO_DB_URI',
  GOOGLE_API_KEY = 'GOOGLE_API_KEY',
  WEATHER_API_KEY = 'WEATHER_API_KEY',
  CRON_TIME = 'CRON_TIME',
}
